version: ci.0.0-{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu18.04
      releaseName: GVNE_x86
      
before_build:
  - sudo apt-get update
  - sudo apt-get install qt5-default qtcreator cmake -y
  - cmake .
build_script:
  - make
